language: python

python:
  - '2.6'
  - '2.7'
  - '3.5'
  - 'nightly'

before_install:
  - pip install --quiet --upgrade pip
  - pip install -r requirements.txt

install:
  - pip install .

cache:
  pip: true
