language: python

python:
  - '2.6'
  - '2.7'
  - '3.5'
  - 'nightly'

before_install:
  - pip install --quiet --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest

install:
  - pip install .

script:
  # no tests just yet, this is required for the build configuration to run
  - pytest

cache:
  pip: true
