language: generic

# only build on master to not duplicate builds when developing
# this can be removed when the 'main' repo is not under duncanmmacleod's
# personal namespace
branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - os: linux
      env: PYTHON_VERSION="2.7"
    - os: linux
      env: PYTHON_VERSION="3.6"
    - os: linux
      env: PYTHON_VERSION="3.7"
    - os: linux
      env: PYTHON_VERSION="3.8"
    - os: osx
      env: PYTHON_VERSION="2.7"
    - os: osx
      env: PYTHON_VERSION="3.6"
    - os: osx
      env: PYTHON_VERSION="3.7"
    - os: osx
      env: PYTHON_VERSION="3.8"

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        curl -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh;
    else
        curl -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
    fi
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - source "${HOME}/miniconda/etc/profile.d/conda.sh"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - travis_retry conda update --quiet --yes conda
  - conda info --all

install:
  # create a conda environment including our requirements
  - travis_retry conda create --quiet --name ci python=${PYTHON_VERSION}
  - travis_retry conda activate ci
  # install testing dependencies with conda
  - travis_retry conda install --quiet --yes --update-deps --name ci --file requirements.txt
  - if [ "${PYTHON_VERSION/./}" -lt 30 ]; then travis_retry conda install --quiet --yes --name ci mock; fi
  # install this version
  - python -m pip install --editable .

script:
  - python -m pytest -rs --verbose --pyargs ciecplib --cov ciecplib --cov-report "" --junitxml=junit.xml
  # run --help on scripts for sanity
  - python -m coverage run --append -m ciecplib.tool.ecp_cert_info --help
  - python -m coverage run --append -m ciecplib.tool.ecp_curl --help
  - python -m coverage run --append -m ciecplib.tool.ecp_get_cert --help
  - python -m coverage run --append -m ciecplib.tool.ecp_get_cookie --help

after_success:
  - travis_retry conda install --quiet --yes --name ci codecov
  - python -m coverage report
  - python -m codecov --flags $(uname) python${PYTHON_VERSION/./}

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
cache:
  pip: true
