name: ciecplib
channels:
  - conda-forge
dependencies:
  - ca-certificates
  - m2crypto
  - pyopenssl
  - python>=3
  - requests
  - requests-ecp
  - setuptools
  - sphinx
  - sphinx-argparse
  - sphinx-automodapi
  - sphinx_rtd_theme
  - pip:
    - sphinx_tabs
